{
 "title": "Ceph - RGW Bucket Usage Overview",
 "tags": [
  "Ceph",
  "RGW"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(custom_rgw_bucket_num_objects, bucket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Object Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_rgw_bucket_num_objects{bucket=~\"$bucket\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Object Count (KiB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_rgw_bucket_size_kb{bucket=~\"$bucket\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bucket Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Number of Objects (per Bucket)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "custom_rgw_bucket_num_objects{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "custom_rgw_user_quota_max_objects * on (instance, uid) group_right custom_rgw_bucket_num_objects{bucket=~\"$bucket\"} > 0",
     "legendFormat": "Max - {{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Size (KiB) (per Bucket)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "custom_rgw_bucket_size_kb{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "custom_rgw_user_quota_max_size_kb + on (instance, uid) group_right custom_rgw_bucket_size_kb{bucket=~\"$bucket\"} > 0",
     "legendFormat": "Max - {{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Size Utilized (KiB) (per Bucket)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "custom_rgw_bucket_size_kb_utilized{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "custom_rgw_user_quota_max_size_kb + on (instance, uid) group_right custom_rgw_bucket_size_kb_utilized{bucket=~\"$bucket\"} > 0",
     "legendFormat": "Max - {{bucket}}"
    }
   ]
  },
  {
   "title": "Actual Bucket Size (KiB) (per Bucket)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "custom_rgw_bucket_size_kb_actual{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "custom_rgw_user_quota_max_size_kb + on (instance, uid) group_right custom_rgw_bucket_size_kb_actual{bucket=~\"$bucket\"} > 0",
     "legendFormat": "Max - {{bucket}}"
    }
   ]
  },
  { "title": "Bucket Quota Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Bucket Quota Max Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "custom_rgw_bucket_quota_max_objects{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Quota Max Size (KiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "custom_rgw_bucket_quota_max_size_kb{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}